services:
  db_old:
    image: mysql:8.0.40
    container_name: rpolitecnica_db_old
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpolitecnica
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    command: --default-authentication-plugin=mysql_native_password

  db:
    image: mysql:8.0.40
    container_name: rpolitecnica_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  db-test:
    image: mysql:8.0.40
    container_name: mysql_rpolitecnica_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpolitecnica_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    tmpfs:
      - /var/lib/mysql  

volumes:
  db_data:
  db_test_data:

